export { default as FormFooter } from "./FormFooter";
export { default as RegisterForm } from "./Register/RegisterForm";
export { default as PasswordValidation } from "./Register/Password/PasswordValidation";
export { default as PasswordValidationField } from "./Register/Password/PasswordValidationField";
export { default as FragmentSwitcher } from "./Register/FragmentSwitcher";
export { default as Password } from "./Register/Password";
export { default as Introduce } from "./Register/Introduce";
export { default as LoginForm } from "./Login/LoginForm";
export { default as SocialForm } from "./SocialForm";
